title: Open World Tech
logo: /assets/img/logo.jpg
logo1: /assets/img/logo1.jpg
logo2: /assets/img/logo2.jpg
logo3: /assets/img/logo3.jpg
logo4: /assets/img/logo4.jpg
description: Open Source, Open World
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
